### ISSUE TITLE
Add support for Entry Types

### ISSUE THREAD

**Issue by benfeather** [verbb/cloner#17] opened 2024-06-20 05:17 UTC
### What are you trying to do?

Craft 5 has separated Sections and Entry Types. 

Sections can be cloned with this plugin but entry types can't be, could this be added?

**Comment by engram-design** [comment] 2024-06-20 06:54
Duplicate of https://github.com/verbb/cloner/issues/16 will tag a release shortly

**Comment by engram-design** [comment] 2024-09-07 12:10
Added in [3.0.1](https://github.com/verbb/cloner/releases/tag/3.0.1)

**Closed as completed by engram-design** 2024-09-07 12:10 UTC
Labels: feature request
